### ISSUE TITLE
extend dosdp_tsv

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/bds-pipeline-config#9]
- [x]  Add column for projection type to _dosdp_tsv. @hkir-dev 
- [x]  Add column for layer to _dosdp_tsv. @hkir-dev 
- [x]  curate projection type (PATO) @shawntanzk 

related to #98

**Comment by hkir-dev** [comment]
New branch 'workshop_dosdp_improvement' created.
- Dosdp [pattern file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/workshop_dosdp_improvement/src/patterns/dosdp-patterns/brainCellRegionMinimalMarkers.yaml)
- Dosdp [data file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/workshop_dosdp_improvement/src/patterns/data/default/brainCellRegionMinimalMarkers.tsv)

This branch uses an older version of the marker file (CS202002013_markers.tsv), since the one in the master is broken. But didn't committed the new one to prevent a future conflict or unintended override.

**Comment by shawntanzk** [comment]
Not 100% sure on the difference between older or newer version of file, but I guess it's ok for me to just curate on this and it will work fine later down the line? 
Either way, will start working on curating projection :)

**Comment by shawntanzk** [comment]
added projections [here](https://github.com/obophenotype/brain_data_standards_ontologies/blob/workshop_dosdp_improvement/src/patterns/data/default/brainCellRegionMinimalMarkers.tsv)
@dosumis - do you want me to add UBERON layers for straightforward ones (those with only 1 layer in name) or should I wait for data on layer information to come out before doing it?
